version: '3'
services:
  # Caddy - Reverse Proxy
  caddy:
    image: abiosoft/caddy
    container_name: "caddy"
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - $HOME/.caddy:/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    environment:
      - CADDYPATH=/etc/caddycerts
      - ACME_AGREE=true
    restart: unless-stopped
  
  # Jellyfin - Multimedia Server
  jellyfin:
    image: "jellyfin/jellyfin"
    container_name: "jellyfin"
    volumes:
      - ./jellyfin:/config
      - /Volumes/HDD1/MEDIA:/media
    ports:
      - "8096:8096"
    restart: always
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Rome

  # Transmission
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - /Volumes/HDD1/MEDIA:/downloads
      - ./transmission:/config
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # Bitwarden - Password Manager
  bitwarden:
    image: mprasil/bitwarden
    container_name: bitwarden
    volumes:
      - ./bitwarden/:/data/
    ports:
      - "9000:80"
    restart: unless-stopped

  # Sonarr - TV Series Manager
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    volumes:
      - ./sonarr:/config
      - /Volumes/HDD1/MEDIA:/media
    ports:
      - 8989:8989
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome

  # Jackett - Torrent Proxy
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    volumes:
      - ./jackett:/config
      - ./jdw:/downloads
    ports:
      - 9117:9117
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
  
  # Guacamole - RDP, VNC, SSH Proxy
  guacamole:
    container_name: guacamole
    restart: unless-stopped
    image: oznu/guacamole
    ports:
      - '8080:8080'
    volumes:
      - './guacamole:/config'
